services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starter-project
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./test:/app/test # This is required to be able to run tests