services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: demo-project-prod
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src