services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-project
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src